language: c++
os: linux
sudo: false
dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-6.0
      - libclang-6.0-dev
      - llvm-6.0-tools
      - python-pip

before_script:
  - mkdir -p "$HOME/install" "$HOME/build"
  - env

script:
  - cd "$HOME/build"
  - cmake "$TRAVIS_BUILD_DIR" -DCMAKE_CXX_COMPILER=clang++-6.0 -DCPACK_GENERATOR="TGZ;DEB" -DLIT_MODULE="/usr/lib/llvm-6.0/build/utils/lit/lit.py"
  - VERBOSE=1 make all
  - VERBOSE=1 make check
  - VERBOSE=1 make package
  - VERBOSE=1 DESTDIR="$HOME/install" make install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6788df84412f2d288bb3
    on_success: change
    on_failure: always
    on_start: never
