language: python
os: linux
sudo: false
dist: xenial

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-8
      - libclang-8-dev
      - llvm-8-tools

install:
  - pip --version
  - pip install --upgrade pip
  - pip install lit

before_script:
  - mkdir -p "$HOME/install" "$HOME/build"
  - env

script:
  - cd "$HOME/build"
  - cmake "$TRAVIS_BUILD_DIR" -DCMAKE_CXX_COMPILER=clang++-8 -DCPACK_GENERATOR="TGZ;DEB"
  - VERBOSE=1 make all
  - VERBOSE=1 make check
  - VERBOSE=1 make package
  - VERBOSE=1 DESTDIR="$HOME/install" make install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6788df84412f2d288bb3
    on_success: change
    on_failure: always
    on_start: never
