language: python

matrix:
  include:
    - os: linux
      sudo: false
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
            - ubuntu-toolchain-r-test
          packages:
            - python-pip
            - cmake
            - clang-8
            - libclang-8-dev
            - llvm-8
            - llvm-8-dev
            - llvm-8-tools
      env:
        - CC=clang-8
        - CXX=clang++-8
        - PATH="/home/travis/bin:/usr/local/cmake-3.12.4/bin:/bin:/usr/bin:/usr/local/bin"
#    - os: osx
#      osx_image: xcode11.2
#      language: generic
#      addons:
#        homebrew:
#          packages:
#            - pipenv
#            - llvm@8
#      env:
#        - CC=clang
#        - CXX=clang++

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      csrutil status || true;
#      brew update;
#    fi

install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      pipenv install lit;
#    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install lit;
    fi

before_script:
  - uname
  - env | sort
  - mkdir -p "$HOME/install" "$HOME/build"
  - cd "$HOME/build"

script:
  - cmake "$TRAVIS_BUILD_DIR" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER="$CXX" -DCPACK_GENERATOR="TGZ;DEB"
  - VERBOSE=1 make all
  - VERBOSE=1 make check
  - VERBOSE=1 make package
  - VERBOSE=1 DESTDIR="$HOME/install" make install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6788df84412f2d288bb3
    on_success: change
    on_failure: always
    on_start: never
